from __future__ import annotations

import json
import random
from pathlib import Path
from typing import Any

from datasets import Dataset, load_dataset, load_from_disk

from graph_verifier.utils.llm import LLMError, complete_json


OUT = Path(__file__).with_name("mvp_cases.jsonl")
LOCAL_DATASET = Path(__file__).with_name("competition_math_train")
TMP_OUT = OUT.with_suffix(".jsonl.tmp")
DATASET = "qwedsacf/competition_math"
SPLIT = "train"
SEED = 7
LIMIT = 100
BATCH_SIZE = 10
ALLOWED_LEVELS = {"Level 1", "Level 2"}
ALLOWED_TYPES = {"Prealgebra", "Algebra", "Counting & Probability"}


def main() -> int:
    rows = ensure_local_dataset()
    selected = select_rows(rows)
    written = read_existing_tmp()

    with TMP_OUT.open("a", encoding="utf-8") as handle:
        for start in range(0, len(selected), BATCH_SIZE):
            batch = selected[start : start + BATCH_SIZE]
            if all(item["source"]["row"] in written for item in batch):
                continue
            generated = generate_batch(batch)
            for item in batch:
                row_id = item["source"]["row"]
                case = generated[row_id]
                item["agent_answer"] = case["agent_answer"]
                item["agent_reasoning"] = case["agent_reasoning"]
                handle.write(json.dumps(item, ensure_ascii=False, sort_keys=True) + "\n")
                handle.flush()
                written.add(row_id)

    if len(written) < LIMIT:
        raise RuntimeError(f"generated {len(written)} cases, expected {LIMIT}")
    TMP_OUT.replace(OUT)
    print(OUT)
    return 0


def ensure_local_dataset() -> Dataset:
    if LOCAL_DATASET.exists():
        return load_from_disk(str(LOCAL_DATASET))
    rows = load_dataset(DATASET, split=SPLIT)
    rows.save_to_disk(str(LOCAL_DATASET))
    return rows


def select_rows(rows: Dataset) -> list[dict[str, Any]]:
    candidates = [
        (index, row)
        for index, row in enumerate(rows)
        if row["level"] in ALLOWED_LEVELS and row["type"] in ALLOWED_TYPES
    ]
    random.Random(SEED).shuffle(candidates)
    selected = []
    for case_number, (index, row) in enumerate(candidates[:LIMIT], 1):
        selected.append(
            {
                "id": f"mvp_{case_number:03d}",
                "question": row["problem"],
                "expected_answer": extract_boxed(row["solution"]),
                "source": {
                    "dataset": DATASET,
                    "split": SPLIT,
                    "row": index,
                    "level": row["level"],
                    "type": row["type"],
                },
                "notes": "agent_answer and agent_reasoning generated by OpenRouter; expected_answer is offline eval only.",
            }
        )
    return selected


def generate_batch(batch: list[dict[str, Any]]) -> dict[int, dict[str, str]]:
    payload = {
        "cases": [
            {
                "source_row": item["source"]["row"],
                "id": item["id"],
                "question": item["question"],
                "level": item["source"]["level"],
                "type": item["source"]["type"],
            }
            for item in batch
        ]
    }
    last_error = ""
    for _ in range(2):
        try:
            response = complete_json("answer_cases.md", payload)
            generated = {}
            for item in response.get("cases", []):
                row_id = int(item["source_row"])
                answer = str(item["agent_answer"]).strip()
                reasoning = str(item["agent_reasoning"]).strip()
                if not answer or not reasoning:
                    raise ValueError(f"empty generation for row {row_id}")
                generated[row_id] = {
                    "agent_answer": answer,
                    "agent_reasoning": reasoning,
                }
            expected = {item["source"]["row"] for item in batch}
            if set(generated) != expected:
                raise ValueError("LLM returned wrong case set")
            return generated
        except (LLMError, KeyError, TypeError, ValueError, json.JSONDecodeError) as exc:
            last_error = str(exc)
    raise RuntimeError(f"OpenRouter generation failed: {last_error}")


def read_existing_tmp() -> set[int]:
    if OUT.exists():
        OUT.unlink()
    if not TMP_OUT.exists():
        return set()
    seen = set()
    with TMP_OUT.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                seen.add(json.loads(line)["source"]["row"])
    return seen


def extract_boxed(solution: str) -> str:
    marker = "\\boxed{"
    start = solution.find(marker)
    if start == -1:
        return ""
    pos = start + len(marker)
    depth = 1
    chars = []
    while pos < len(solution) and depth:
        char = solution[pos]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                break
        chars.append(char)
        pos += 1
    return "".join(chars).strip()


if __name__ == "__main__":
    raise SystemExit(main())
